GSTR2A/urls.py
from django.urls import path
from . import views

app_name = 'GST2A'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('GST2Aindex/',views.GST2Aindex.as_view(),name='GST2Aindex'),
    path('CreateGST2A/',views.CreateGST2A.as_view(),name='CreateGST2A'),
    path('UpdateGSTR2A/<int:pk>/',views.UpdateGSTR2A.as_view(),name='UpdateGSTR2A'),
    path('GSTR2AList/',views.GSTR2AList.as_view(),name='GSTR2AList'),
    path('GSTR2ADeleteView/<int:pk>/',views.GSTR2ADeleteView.as_view(),name='GSTR2ADeleteView'),
    path('search/',views.search,name='search'),
    path('gst2Input/',views.gst2Input,name='gst2Input'),
    path('GSTR2AFilling/',views.GSTR2AFilling,name='GSTR2AFilling'),
    path('autocomplete/',views.autocomplete,name='autocomplete'),
    path('autocomplete_gst_no/',views.autocomplete_gst_no,name='autocomplete_gst_no'),
    path('autocomplete_Supplier/',views.autocomplete_Supplier,name='autocomplete_Supplier'),
    path('DetailGSTR2A/<int:pk>/',views.DetailGSTR2A.as_view(),name='DetailGSTR2A'),
    
    
]

adminreport/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views


app_name = 'adminrep'

urlpatterns = [

    path('NewCustForm/',views.NewCustForm,name='NewCustForm'),
    path('payment/',views.payment,name='payment'),
    #path('delete/<int:pk>/',views.printDeleteView.as_view(),name='delete'),
    path('Invsearch/',views.Invsearch,name='Invsearch'),
    url(r'^Invsearch/(?P<Inv>\w+)/(?P<q>\w+)/$',views.Invsearch,name='Invsearch'),
    #re_path(r'^Invsearch\.+$',views.Invsearch,name='Invsearch'),
    path('paymentupdate/',views.paymentupdate,name='paymentupdate'),
    path('GST1/',views.GST1,name='GST1'),
    path('gst1Input/',views.gst1Input,name='gst1Input'),
    path('cancelInv/',views.cancelInv,name='cancelInv'),
    path('autocomplete_cust_search/',views.autocomplete_cust_search,name='autocomplete_cust_search'),
    path('oldCustForm/',views.oldCustForm,name='oldCustForm'),
    path('updateCustEntry/<int:pk>/',views.updateCustEntry.as_view(),name='updateCustEntry'),
    path('CustEntryView/',views.CustEntryView.as_view(),name='CustEntryView'),
    path('<int:pk>/',views.custDetailView.as_view(),name='detail'),
    


]

bill/urls.py
from django.urls import path
from . import views

app_name = 'bill'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('admin/',views.AdminView.as_view(),name='admin'),
    path('report/',views.ReportView.as_view(),name='report'),
    #path('print/',views.printView.as_view(),name='print'),
    path('admin_gst_list/',views.gstAdminListView.as_view(),name='admin_gst_list'),
    path('admin_nogst_list/',views.nogstAdminListView.as_view(),name='admin_nogst_list'),
    path('gst_list/',views.gstListView.as_view(),name='gst_list'),
    path('nogst_list/',views.nogstListView.as_view(),name='nogst_list'),
    path('create/',views.CreateSaleEntry.as_view(),name='create'),
    path('<int:pk>/',views.gstDetailView.as_view(),name='detail'),
    path('update/<int:pk>/',views.updateSaleEntry.as_view(),name='update'),
    path('delete/<int:pk>/',views.billDeleteView.as_view(),name='delete'),
    path('view/',views.viewSales.as_view(),name='viewSales'),
    path('search/',views.search,name='search'),
    path('search-form/', views.search_form,name='search-form'),
    path('Estimate/', views.Estimate,name='Estimate'),
    path('Invoice/', views.Invoice,name='Invoice'),
    path('stock/', views.stock.as_view(),name='stock'),
    path('stateOfSupply/',views.stateOfSupply,name='stateOfSupply'),
    path('autocomplete/', views.autocomplete,name='autocomplete'),
    path('autocomplete_Catogory/', views.autocomplete_Catogory,name='autocomplete_Catogory'),
]

billing/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from bill import views
from django.conf.urls import url
#from print import views

urlpatterns = [
    path('',views.IndexView.as_view()),
    #path('',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('admin/',admin.site.urls,name='admin'),
    path('bill/',include('bill.urls',namespace='bill')),
    path('print/',include('print.urls',namespace='print')),
    path('adminrep/',include('adminreport.urls',namespace='adminrep')),
    path('GST2A/',include('GSTR2A.urls',namespace='GST2A')),
    path('itemreturn/',include('itemreturn.urls',namespace='itemreturn')),

    
]

print/urls.py
from django.urls import path
from . import views


app_name = 'print'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('printview/',views.printview.as_view(),name='printview'),
    path('post_print_Form/',views.post_print_Form,name='post_print_Form'),
    path('update_print_Form/<int:pk>',views.update_print_Form,name='update_print_Form'), 
    path('get_print_Form/', views.get_print_Form,name='get_print_Form'),
    path('viewprint/',views.viewprint,name='viewprint'),
    path('delete/<int:pk>/',views.printDeleteView.as_view(),name='delete'),
    path('InvoicePrint/',views.InvoicePrint,name='InvoicePrint'),
    path('quick_print_Form/',views.quick_print_Form,name='quick_print_Form'),
    path('autocomplete/', views.autocomplete,name='autocomplete'),
    path('testPrint/', views.testPrint,name='testPrint'),
    
    
]

GSTR2A/models.py
import re
from django.db import models
from django.urls import reverse
from django.db.models import Q

# Create your models here.
class GSRT2A_supplier_id(models.Model):
    supplier_id = models.AutoField(primary_key=True)
    GSTIN_of_Supplier=models.CharField(max_length=15)

class GSRT2A(models.Model):
    id = models.AutoField(primary_key=True)
    Supplier_name = models.CharField(max_length=100)
    GSTIN_of_Supplier=models.CharField(max_length=15)
    Invoice_number=models.CharField(max_length=20)
    Invoice_date= models.DateField()
    Received_date=models.DateField(null=True,blank=True)
    Amount_No_Tax =models.FloatField()
    SGST_Tax=models.FloatField(null=True,blank=True)
    CGST_Tax =models.FloatField(null=True,blank=True)
    IGST_Tax = models.FloatField(null=True,blank=True)
    supplier_id = models.PositiveIntegerField()
    Total_Amount =models.FloatField()
    

    @property
    def get_supplier_id(self):
        model = GSRT2A_supplier_id
        search_result =model.objects.filter(GSTIN_of_Supplier=self.GSTIN_of_Supplier).first()
        print(search_result)
        if search_result is None:
            insert_dict = {'GSTIN_of_Supplier':self.GSTIN_of_Supplier}
            model.objects.create(**insert_dict)
            search_result =model.objects.filter(GSTIN_of_Supplier=self.GSTIN_of_Supplier).first()
            #print(search_result)
            ret_val = search_result.supplier_id
        else:
            ret_val = search_result.supplier_id
        
        return ret_val
    
    @property
    def get_SGST_Tax(self):
        if self.SGST_Tax == None:
            SGST_Tax=0.0
            return SGST_Tax

    @property
    def get_CGST_Tax(self):
        if self.CGST_Tax == None:
            CGST_Tax=0.0
            return CGST_Tax

    @property
    def get_IGST_Tax(self):
        if self.IGST_Tax == None:
            IGST_Tax=0.0
            return IGST_Tax

    @property
    def get_Total_Amount(self):
        if self.SGST_Tax == None:
            self.SGST_Tax =self.get_SGST_Tax 
        if self.CGST_Tax == None:
            self.CGST_Tax =self.get_CGST_Tax
        if self.IGST_Tax == None:
            self.IGST_Tax =self.get_IGST_Tax
        Total_Amount = self.Amount_No_Tax +self.CGST_Tax+self.SGST_Tax+self.IGST_Tax
        return Total_Amount

    def save(self, *args,**kwargs):
        self.supplier_id = self.get_supplier_id
        self.Total_Amount = self.get_Total_Amount
        super(GSRT2A, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("GST2A:DetailGSTR2A",kwargs={'pk': self.pk})

class GSRT2A_payment(models.Model):
    id =models.AutoField(primary_key=True)
    GSTIN_of_Supplier=models.CharField(max_length=15)
    Supplier_name = models.CharField(max_length=100)
    Invoice_number=models.CharField(max_length=20)
    payment_Amount = models.FloatField()
    payment_left = models.FloatField()
    current_payment_Date = models.DateField()
    supplier_id = models.PositiveIntegerField()
    Comment = models.CharField(max_length=200)
    is_last = models.BooleanField()

GSTR2A/forms.py
from django import forms
from django.forms import ModelForm
from .models import GSRT2A
from django.contrib.admin.widgets import AdminDateWidget

class DateInput(forms.DateInput):
    input_type = 'date'


class CreateGSTR2AForm(ModelForm):
    class Meta:
        model = GSRT2A
        fields =['Supplier_name','GSTIN_of_Supplier','Invoice_number','Invoice_date','Received_date','Amount_No_Tax','SGST_Tax','CGST_Tax',
        'IGST_Tax']
    #supplier_id = models.PositiveIntegerField()
        widgets = {
            'Invoice_date': DateInput(),
            'Received_date': DateInput(),

        }
    
class UpdateGSTR2AForm(ModelForm):
    class Meta:
        model = GSRT2A
        fields =['Invoice_number','Invoice_date','Received_date','Amount_No_Tax','SGST_Tax','CGST_Tax','IGST_Tax']
        widgets = {
            'Invoice_date': DateInput(),
            'Received_date': DateInput(),

        }
    

GSTR2A/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from .forms import CreateGSTR2AForm,UpdateGSTR2AForm
from django.views.generic import TemplateView,DetailView,ListView,DeleteView,CreateView,UpdateView
from .models import GSRT2A
from django.urls import reverse_lazy,reverse
import os,csv
from django.db.models import Q
from django.db import connection
import re,datetime


#  bill index page
class IndexView(TemplateView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'index.html'

class GST2Aindex(TemplateView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'GSTR2A/GST2A-main.html'

class CreateGST2A(CreateView):
    model = GSRT2A
    form_class = CreateGSTR2AForm

class UpdateGSTR2A(UpdateView):
    model = GSRT2A
    form_class = UpdateGSTR2AForm

class DetailGSTR2A(DetailView):
    context_object_name = 'GSTR2A'
    model = GSRT2A
    template_name = 'GSTR2A/supplier_details.html'

class GSTR2ADeleteView(DeleteView):
    template_name = 'GSTR2A/GSRT2A_confirm_delete.html'
    model = GSRT2A
    context_object_name = 'deleteGSRT2A'
    success_url = reverse_lazy("GST2A:gst2Input")

class GSTR2AList(ListView):

    model = GSRT2A
    context_object_name = 'viewGSRT2A'
    template_name = 'GSTR2A/view_GSRT2A.html'

def search(request):
    model = GSRT2A
    error = False
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            error = True
        else:
            viewGSRT2A = model.objects.filter(Invoice_number=q)
            return render(request, 'GSTR2A/view_GSRT2A.html', {'viewGSRT2A': viewGSRT2A, 'query': q})
    return render(request, 'bill/index.html', {'error': error})

def autocomplete_Supplier(request):
    model = GSRT2A
    q= request.GET.get('term')
    print(q)
    qs =model.objects.filter(Q(Supplier_name__icontains = q)|Q(GSTIN_of_Supplier__istartswith = q))
    item_name_lst =list()
    for item in qs.values():
        val = "GST Num:"+item['GSTIN_of_Supplier']+','+"Name:"+item['Supplier_name']
        if val not in item_name_lst:
            item_name_lst.append(val)
        #item_cat_lst.append(item['Item_Catogory'])
        #item_sp_lst.append(item['Rate_Of_Sale'])
        
    return JsonResponse(item_name_lst,safe=False)

def GSTR2AFilling(request):
    
    model = GSRT2A
    startdate = request.GET.get('id_start_date')
    enddate = request.GET.get('id_end_date')
    Supplier = request.GET.get('id_Supplier')
    due_or_all = request.GET.get('id_due_or_all')
    #print(Supplier)
    if startdate == "":
        startdate = datetime.datetime(2018, 1, 1)
    if enddate =="":
        enddate = datetime.datetime.now()
    if re.search('GST\sNum\:.+,Name\:.+$',Supplier):
        m = re.search('GST\sNum\:(.+),Name\:(.+)$',Supplier)
        qs =model.objects.filter(Q(Supplier_name__iexact=m.group(2))&Q(GSTIN_of_Supplier__istartswith = m.group(1))&Q(Invoice_date__range=(startdate, enddate))).order_by('Invoice_date')
    else:
        qs =model.objects.filter(Q(Invoice_date__range=(startdate, enddate))).order_by('Invoice_date')
    #print(qs)
    return render(request, 'GSTR2A/gst2_rep.html', {'search_result': qs})
    

def gst2Input(request):
    print("gst1Input")
    return render(request,'GSTR2A/gst2.html')

def autocomplete(request):
    model = GSRT2A
    q= request.GET.get('term')
    qs =model.objects.filter(Supplier_name__istartswith = q)
    item_name_lst =list()
    for item in qs.values():
        #print(item)
        sp = item['Supplier_name']
        if sp not in item_name_lst:
            item_name_lst.append(sp)   
    return JsonResponse(item_name_lst,safe=False)

def autocomplete_gst_no(request):
    model = GSRT2A
    q= request.GET.get('term')
    qs =model.objects.filter(GSTIN_of_Supplier__istartswith = q)
    item_name_lst =list()
    for item in qs.values():
        #print(item)
        sp = item['GSTIN_of_Supplier']
        if sp not in item_name_lst:
            item_name_lst.append(sp)   
    return JsonResponse(item_name_lst,safe=False)

templates/GSTR2A/GSRT2A_confirm_delete.html
{% extends "base.html" %}

{% block body_block %}
<h1>Delete {{deleteGSRT2A.GSTIN_of_Supplier}} and Invoice No {{deleteGSRT2A.Invoice_number}}?</h1>

<form method="post" onsubmit="myButton.disabled = true; return true;">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'print:viewprint' %} ">Cancel</a>


</form>

{% endblock %}

templates/GSTR2A/GST2A-main.html
{% extends "base.html" %}
{% block body_block %}
<center><h1>Supplier Main Page</h1></center>
<br>

<form class="form-inline my-2 my-lg-0" action="/GST2A/search" method="get" onsubmit="myButton.disabled = true; return true;">

    <h4>Supplier Invoice No &nbsp;</h4>
    <input class="form-control mr-sm-2" type="text" placeholder="Search" name="q" required>
      <button class="btn btn-secondary my-2 my-sm-0 button1" type="submit">Search</button>
    </form>
    <br>
<a class="nav-link" href="{% url 'GST2A:CreateGST2A' %}"><button type="button" class="btn btn-success">Add New Supplier Bill</button></a>
<a class="nav-link" href="{% url 'GST2A:GSTR2AList' %}"><button type="button" class="btn btn-success">View Supplier Bill (Edit/Delete)</button></a>
{% endblock %}

templates/GSTR2A/gsrt2a_form.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
<script>
    $( function() {
      var availableTags = [
        
      ];
      $( "#id_Supplier_name" ).autocomplete({
        source: "{% url 'GST2A:autocomplete'%}"
      });
    } );
  </script>
<script>
    $( function() {
      var availableTags = [
        
      ];
      $( "#id_GSTIN_of_Supplier" ).autocomplete({
        source: "{% url 'GST2A:autocomplete_gst_no'%}"
      });
    } );
  </script>
<h1><center>Supplier Bill adding</center></h1>
<form method ='POST' onsubmit="myButton.disabled = true; return true;">
{% csrf_token %}
{% include 'form_template.html' %}
<div class="col-sm-offset-2 col-sm-10">
    <input type="submit"  name = "myButton" class='btn btn-success' value="Submit">



{% endblock %}

templates/GSTR2A/gst2.html
{% extends "base.html" %}
{% block body_block %}
<script>
  $( function() {
    var availableTags = [
      
    ];
    $( "#id_Supplier" ).autocomplete({
      source: "{% url 'GST2A:autocomplete_Supplier'%}"
    });
  } );
</script>
<center><h1>Purchase report</h1></center>

<form action="/GST2A/GSTR2AFilling" method="get" onsubmit="myButton.disabled = true; return true;">
<div class="form-group row">
    <label class="col-sm-2 col-form-label" for="id_Supplier"><b>Supplier</b></label></label>
  <div class="col-sm-10">
    <input  class="form-control" type="text" name="id_Supplier" id="id_Supplier">
   </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label" for="id_due_or_all"><b>Due or All report</b></label></label>
  <div class="col-sm-10">
    <select class="form-control" id="id_due_or_all" name="id_due_or_all">
<option value="All">All</option>
<option value="Due">Due</option>
</select>
    </div>
  </div>

  <div class="form-group row" >
    <label class="col-sm-2 col-form-label" for="id_start_date"><b>Start Date(Billing date):</b></label></label>
  <div class="col-sm-10">
    <input class=class="form-control" type="date" name="id_start_date" id="id_start_date">

  </div>
</div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"  for="id_end_date"><b>End Date(Billing date):</b></label></label>
  <div class="col-sm-10">
    <input  type="date" name="id_end_date" id="id_end_date">
    </div>
  </div>
  <div class="form-group row">
  <input type="submit" class='btn btn-success' value="Submit">&nbsp;&nbsp;&nbsp;&nbsp;
  <input type="reset" class='btn btn-secondary' value="reset">
  </div>
  </form>


{% endblock %}

templates/GSTR2A/gst2_form_search.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<script>
    $( function() {
      var availableTags = [
        
      ];
      $( "#id_cust_name" ).autocomplete({
        source: "{% url 'adminrep:autocomplete_cust_search'%}"
      });
    } );
  </script>
<center><h1>sales report</h1></center>

<form  action="/adminrep/GST1" method="get" onsubmit="myButton.disabled = true; return true;">
<div class="form-group row">
      <label class="col-sm-2 col-form-label" for="id_cust_name"><b>Customer Name/All:</b></label></label>
	  <div class="col-sm-10">
      <input  class="form-control" type="text" name="id_cust_name" placeholder ='Customer Name/All'required id="id_cust_name">
     </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="id_due_or_all"><b>Due or All report</b></label></label>
	  <div class="col-sm-10">
      <select class="form-control" id="id_due_or_all" name="id_due_or_all">
  <option value="All">All</option>
  <option value="Due">Due</option>
  </select>
      </div>
	  </div>

    <div class="form-group row" >
      <label class="col-sm-2 col-form-label" for="id_start_date"><b>Start Date(Billing date):</b></label></label>
	  <div class="col-sm-10">
      <input class=class="form-control" type="date" name="id_start_date"  required id="id_start_date">
 
    </div>
	</div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label"  for="id_end_date"><b>End Date(Billing date):</b></label></label>
	  <div class="col-sm-10">
      <input  type="date" name="id_end_date"  required id="id_end_date">
      </div>
    </div>
    <div class="form-group row">
    <input type="submit" class='btn btn-success' value="Submit">&nbsp;&nbsp;&nbsp;&nbsp;
    <input type="reset" class='btn btn-secondary' value="reset">
    </div>
    </form>

{% endblock %}

templates/GSTR2A/gst2_rep.html
{% extends "base.html" %}
{% block body_block %}
<center><h1>Purchase report</h1></center>

<table class="table table-bordered table-condensed">
    <thead>
        <tr>
        <th>Supplier_name</th>
        <th>GSTIN_of_Supplier</th>
        <th>Invoice_number</th>
        <th>Invoice_date</th>
        <th>Amount_No_Tax</th>
        <th>SGST_Tax</th>
        <th>CGST_Tax</th>
        <th>IGST_Tax</th>
        <th>Total</th>
        <th>Edit</th>
        <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in search_result %}
            
            <td>{{ obj.Supplier_name }}</td>
            <td>{{ obj.GSTIN_of_Supplier }}</td>
            <td>{{ obj.Invoice_number}}</td>
            <td>{{ obj.Invoice_date }}</td>
            <td>{{ obj.Amount_No_Tax }}</td>
            <td>{{ obj.SGST_Tax }}</td>
            <td>{{ obj.CGST_Tax }}</td>
            <td>{{ obj.IGST_Tax }}</td>
            <td>{{ obj.Total_Amount }}</td>
            <td><a href="{% url 'GST2A:UpdateGSTR2A' obj.id %}">edit</a></td>
            <td><a class="btn btn-danger" href="{% url 'GST2A:GSTR2ADeleteView' obj.id %}">delete</a></td>
        </tr>
{% endfor %}

{% endblock %}

templates/GSTR2A/supplier_details.html
{% extends "base.html" %}
{% block body_block %}
<p class="container">
  <div class="jumbotron">
    <h1><center>Detail</center></h1>
    
    <p><label class="control-label col-sm-2" >Supplier name</label>:<b> {{GSTR2A.Supplier_name}}</b> </p>
    <p><label class="control-label col-sm-2" >GSTIN of Supplier</label>: {{GSTR2A.GSTIN_of_Supplier}}</p>
    <p><label class="control-label col-sm-2" >Invoice number</label>: {{GSTR2A.Invoice_number}}</p>
    <p><label class="control-label col-sm-2" >Invoice date</label>: {{GSTR2A.Invoice_date}}</p>
    <p><label class="control-label col-sm-2" >Product Receive Date</label>: {{GSTR2A.Received_date}}</p>
    <p><label class="control-label col-sm-2" >Amount Without Tax</label>: {{GSTR2A.Amount_No_Tax}}</p>
    <p><label class="control-label col-sm-2" >SGST Amount</label>: {{GSTR2A.SGST_Tax}}</p>
    <p><label class="control-label col-sm-2" >CGST Amount</label>: {{GSTR2A.CGST_Tax}}</p>
    <p><label class="control-label col-sm-2" >IGST Amount</label>: {{GSTR2A.IGST_Tax}}</p>
    <p><label class="control-label col-sm-2" >Total Amount</label>: {{GSTR2A.Total_Amount}}</p>
    <div class="btn-group" >
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'GST2A:CreateGST2A' %}"><button type="button" class="btn btn-warning button2">Create New</button></a>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'GST2A:UpdateGSTR2A' GSTR2A.id %}"><button type="button" class="btn btn-danger button2">Update</button></a>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'GST2A:GSTR2AList'%}"><button type="button" class="btn btn-success button2" >Show all details</button></a>
    
  </div>
  </div>
  

        

  </div>


{% endblock %}

templates/GSTR2A/view_GSRT2A.html
{% extends "base.html" %}
{% block body_block %}
<h1>Bill Of Suppliers</h1>

<table border="1">
<thead>
    <tr>
<th>Name_of_Supplier</th>
<th>GSTIN_of_Supplier</th>
<th>Invoice_number</th>
<th>Invoice_date</th>
<th>Product_receive_date</th>
<th>Taxable_value</th>
<th>SGST_Tax</th>
<th>CGST_Tax</th>
<th>IGST_Tax</th>
<th>Total</th>
  </tr>
        {% for obj in viewGSRT2A %}
      <tr>
        <td>{{ obj.Supplier_name}}</td>
<td>{{ obj.GSTIN_of_Supplier}}</td>
<td>{{ obj.Invoice_number}}</td>
<td>{{ obj.Invoice_date}}</td>
<td>{{ obj.Received_date}}</td>
<td>{{ obj.Amount_No_Tax}}</td>
<td>{{ obj.SGST_Tax}}</td>
<td>{{ obj.CGST_Tax}}</td>
<td>{{ obj.IGST_Tax}}</td>
<td>{{ obj.Total_Amount}}</td>
        <td><a href="{% url 'GST2A:UpdateGSTR2A' obj.pk %}">edit</a></td>
        <td><a class="btn btn-danger" href="{% url 'GST2A:GSTR2ADeleteView' obj.pk %}">delete</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>
{% endblock %}