adminreport/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views


app_name = 'adminrep'

urlpatterns = [

    path('NewCustForm/',views.NewCustForm,name='NewCustForm'),
    path('payment/',views.payment,name='payment'),
    #path('delete/<int:pk>/',views.printDeleteView.as_view(),name='delete'),
    path('Invsearch/',views.Invsearch,name='Invsearch'),
    url(r'^Invsearch/(?P<Inv>\w+)/(?P<q>\w+)/$',views.Invsearch,name='Invsearch'),
    #re_path(r'^Invsearch\.+$',views.Invsearch,name='Invsearch'),
    path('paymentupdate/',views.paymentupdate,name='paymentupdate'),
    path('GST1/',views.GST1,name='GST1'),
    path('gst1Input/',views.gst1Input,name='gst1Input'),
    path('cancelInv/',views.cancelInv,name='cancelInv'),
    path('autocomplete_cust_search/',views.autocomplete_cust_search,name='autocomplete_cust_search'),
    path('oldCustForm/',views.oldCustForm,name='oldCustForm'),
    path('updateCustEntry/<int:pk>/',views.updateCustEntry.as_view(),name='updateCustEntry'),
    path('CustEntryView/',views.CustEntryView.as_view(),name='CustEntryView'),
    path('<int:pk>/',views.custDetailView.as_view(),name='detail'),
    


]

bill/urls.py
from django.urls import path
from . import views

app_name = 'bill'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('admin/',views.AdminView.as_view(),name='admin'),
    path('report/',views.ReportView.as_view(),name='report'),
    #path('print/',views.printView.as_view(),name='print'),
    path('admin_gst_list/',views.gstAdminListView.as_view(),name='admin_gst_list'),
    path('admin_nogst_list/',views.nogstAdminListView.as_view(),name='admin_nogst_list'),
    path('gst_list/',views.gstListView.as_view(),name='gst_list'),
    path('nogst_list/',views.nogstListView.as_view(),name='nogst_list'),
    path('create/',views.CreateSaleEntry.as_view(),name='create'),
    path('<int:pk>/',views.gstDetailView.as_view(),name='detail'),
    path('update/<int:pk>/',views.updateSaleEntry.as_view(),name='update'),
    path('delete/<int:pk>/',views.billDeleteView.as_view(),name='delete'),
    path('view/',views.viewSales.as_view(),name='viewSales'),
    path('search/',views.search,name='search'),
    path('search-form/', views.search_form,name='search-form'),
    path('Estimate/', views.Estimate,name='Estimate'),
    path('Invoice/', views.Invoice,name='Invoice'),
    path('stock/', views.stock.as_view(),name='stock'),
    path('stateOfSupply/',views.stateOfSupply,name='stateOfSupply'),
    path('autocomplete/', views.autocomplete,name='autocomplete'),
    path('autocomplete_Catogory/', views.autocomplete_Catogory,name='autocomplete_Catogory'),
]

billing/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from bill import views
from django.conf.urls import url
#from print import views

urlpatterns = [
    path('',views.IndexView.as_view()),
    #path('',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('admin/',admin.site.urls,name='admin'),
    path('bill/',include('bill.urls',namespace='bill')),
    path('print/',include('print.urls',namespace='print')),
    path('adminrep/',include('adminreport.urls',namespace='adminrep')),
    path('GST2A/',include('GSTR2A.urls',namespace='GST2A')),
    path('itemreturn/',include('itemreturn.urls',namespace='itemreturn')),

    
]

print/urls.py
from django.urls import path
from . import views


app_name = 'print'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('printview/',views.printview.as_view(),name='printview'),
    path('post_print_Form/',views.post_print_Form,name='post_print_Form'),
    path('update_print_Form/<int:pk>',views.update_print_Form,name='update_print_Form'), 
    path('get_print_Form/', views.get_print_Form,name='get_print_Form'),
    path('viewprint/',views.viewprint,name='viewprint'),
    path('delete/<int:pk>/',views.printDeleteView.as_view(),name='delete'),
    path('InvoicePrint/',views.InvoicePrint,name='InvoicePrint'),
    path('quick_print_Form/',views.quick_print_Form,name='quick_print_Form'),
    path('autocomplete/', views.autocomplete,name='autocomplete'),
    path('testPrint/', views.testPrint,name='testPrint'),
    
    
]

adminreport/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class CustDetail(models.Model):
    Cust_Id =models.AutoField(primary_key=True)
    Customer_Name = models.CharField(max_length=65)
    Address = models.CharField(max_length=200, null=True)
    City = models.CharField(max_length=100)
    State = models.CharField(max_length=50,null=True)
    Mob_No = models.CharField(max_length=50,null=True)
    GSTN_of_Customer = models.CharField(max_length=50, null=True,blank=True)

    def __int__(self):
        return self.CustId
    
    def get_absolute_url(self):
        #print(Item_Name)
        return reverse("adminrep:detail", kwargs={'pk': self.pk})

class SaleReport(models.Model):
    Inv_Type =models.CharField(max_length=5)
    Inv_No =models.PositiveIntegerField()
    Inv_Date = models.DateField(auto_now=True)
    Item_Code = models.CharField(max_length=30)
    Item_Name = models.CharField(max_length=500)
    Item_Catogory =models.CharField(max_length=50)
    Hsn_Code = models.CharField(max_length=10)
    Quatity_Bought_Sale = models.FloatField()
    Unit_Sale = models.CharField(max_length=20)
    Unit_Conversion_Val_GST =models.PositiveIntegerField()
    Converted_Unit_GST =models.CharField(max_length=20)
    Converted_Unit_Val_GST =models.FloatField()
    Unit_Price_Sale = models.FloatField(blank=True, null=True)
    Unit_Nett_Price_Sale = models.FloatField(blank=True, null=True)
    Igst_Percent_Sale = models.FloatField(blank=True, null=True)
    Cgst_Percent_Sale = models.FloatField(blank=True, null=True)
    Sgst_Percent_Sale = models.FloatField(blank=True, null=True)
    Igst_Tot_Sale = models.FloatField(blank=True, null=True)
    Cgst_Tot_Sale = models.FloatField(blank=True, null=True)
    Sgst_Tot_Sale = models.FloatField(blank=True, null=True)
    Total_No_Tax_Sale =models.FloatField()
    Total_Sale = models.FloatField()
    Cgst_Percent_Purchase = models.FloatField(blank=True, null=True)
    Sgst_Percent_Purchase = models.FloatField(blank=True, null=True)
    Igst_Percent_Purchase = models.FloatField(blank=True, null=True)
    Cgst_Tot_Purchase = models.FloatField(blank=True, null=True)
    Sgst_Tot_Purchase = models.FloatField(blank=True, null=True)
    Igst_Tot_Purchase = models.FloatField(blank=True, null=True)
    Unit_Price_Purchase = models.FloatField()
    Total_Purchase = models.FloatField()
    Total_No_Tax_Purchase = models.FloatField()
    Profit = models.FloatField()
    Profit_Percent = models.FloatField()
    Bill_Cancel = models.CharField(max_length=10,choices=(('Yes','Yes'),('No','No')),null=True)
    comment =models.CharField(max_length=100,null=True)
    Bill_cancel_Date = models.DateField(null=True)
    place_of_supply = models.CharField(max_length=100)
    mis1 = models.CharField(max_length=100)
    mis2 = models.CharField(max_length=100)
    mis3 =models.CharField(max_length=100)
    Cust_Id =models.ForeignKey(CustDetail,on_delete='DO_NOTHING',related_name='customerId')


    def __int__(self):
        return self.Inv_No

class invoicenumber(models.Model):
    Inv_No =models.AutoField(primary_key=True)
    Cust_Id =models.ForeignKey(CustDetail,on_delete='DO_NOTHING',related_name='cusId')

class estimatenumber(models.Model):
    Inv_No =models.AutoField(primary_key=True)
    Cust_Id =models.ForeignKey(CustDetail,on_delete='DO_NOTHING',related_name='cusId1')


    def __int__(self):
        return self.Inv_No

class Cust_payment_record(models.Model):
    id =models.AutoField(primary_key=True)
    inv_type = models.CharField(max_length=5)
    inv_number = models.PositiveIntegerField()
    payment_Amount = models.FloatField()
    payment_left = models.FloatField()
    total_bill_Amount = models.FloatField()
    current_payment_Date = models.DateField()
    Comment = models.CharField(max_length=200)
    Cust_Id =models.PositiveIntegerField()
    is_last = models.BooleanField()


    def __int__(self):
        return self.inv_number

adminreport/forms.py
from django import forms
from django.forms import widgets

class CustForm(forms.Form):  
    #CustId =forms.NumberInput(widget = forms.HiddenInput(), required = False)
    Customer_Name           = forms.CharField()
    Address          = forms.CharField(required = False)
    City          = forms.CharField()
    Mob_No                 = forms.CharField()
    GSTN_of_Customer                = forms.CharField(required = False)

class DateInput(forms.DateInput):
    input_type ='date'
    
class salesForm(forms.Form):
    payment_Amount = forms.FloatField()
    
class payment_udpate(forms.Form):
    payment_Amount = forms.FloatField()
    Comment = forms.CharField(required = False)
    current_payment_Date = forms.DateField( widget = DateInput)

class cancleInvoice(forms.Form):
    Bill_Cancel = forms.ChoiceField(choices=(('Yes','Yes'),('No','No')))
    Bill_cancel_Date = forms.DateField( widget = DateInput)
    comment =forms.CharField()

templates/adminreport/Search_Inv.html
{% extends "base.html" %}
{% block body_block %}
<h2>Bill Details for {{inv}} - {{q}}</h2>
<hr>
    {% for obj in CustDetails %}
    <h4>Customer details</h4>
    <table class="table table-striped table table-bordered">
  <thead>
    <tr>
      <th scope="col">Name of Customer</th>
      <th scope="col">Address</th>
      <th scope="col">Mob No</th>
      <th scope="col">GSTIN</th>
      <th scope="col">City</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{obj.Customer_Name}}</th>
      <td>{{obj.Address_Line_1}}</td>
      <td>{{obj.Mob_No}}</td>
      <td>{{obj.GSTN_of_Customer}}</td>
      <td>{{obj.City}}</td>

    </tr>
      </tbody>
</table>

{% endfor %}
<hr>
<table class="table-active">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Item Name</th>
      <th scope="col">Hsn_Code</th>
      <th scope="col">Quatity Bought</th>
      <th scope="col">Sale Price</th>
      <th scope="col">Total(Nett.)</th>
    </tr>
  </thead>
<h4>Item in Invoice</h4>
    {% for obj in search_result %}
    
    
  <tbody>
    <tr>
    <th class="table-info">{{forloop.counter}}</th>
      <td class="table-info">{{obj.Item_Name}}({{obj.Item_Catogory}})</td>
      <td class="table-info">{{obj.Hsn_Code}}</td>
      <td class="table-info">{{obj.Quatity_Bought_Sale}} {{obj.Unit_Sale}}</td>
      <td class="table-info">{{obj.Unit_Nett_Price_Sale}}</td>
      <td class="table-info">{{obj.Total_Sale}}</td>

    </tr>
      

{% endfor %}
</tbody>
</table>
<hr>
<table class="table-active">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Payment Date</th>
      <th scope="col">Payment Amount</th>
      <th scope="col">Due Left</th>
      <th scope="col">Comment</th>
      
    </tr>
  </thead>
<h4>Payment History</h4>
    {% for pay in payment_history %}
  <tbody>
    <tr>
    <th class="table-info">{{forloop.counter}}</th>
    <td class="table-info">{{pay.current_payment_Date}}</td>
      <td class="table-info">{{pay.payment_Amount}}</td>
      <td class="table-info">{{pay.payment_left}}</td>
      <td class="table-info">{{pay.Comment}}</td>
    </tr>
      

{% endfor %}
</tbody>
</table>
<br>
{% for obj in search_result|slice:":1" %}

Is Bill cancelled : {{ obj.Bill_Cancel}}<br>
{% ifequal  obj.Bill_Cancel 'Yes' %} 
Total Bill amount : <del>{{ grandTotal }}</del><br>
    Total need to pay : <b><del>{{ left_amount}}</del></b><br>
    Bill Cancel reason :<b>{{obj.comment}}</b><br> 
    <br/>
<br/>

<center><a href="{% url 'print:InvoicePrint' %}"><button type="button" class="btn btn-danger button3">Print bill</button></a>


    
{% else %} 
    Total Bill amount : {{ grandTotal }}<br>
    Total need to pay : <b>{{ left_amount}}</b><br> 
    <br/>
<br/>

<a href="{% url 'print:InvoicePrint' %}"><button type="button" class="btn btn-danger button3">Print bill</button></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="{% url 'adminrep:paymentupdate' %}"><button type="button" class="btn btn-danger button3">Update Payment</button></a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="{% url 'adminrep:cancelInv' %}"><button type="button" class="btn btn-danger button3">Cancel Bill</button></a></center>
{% endifequal %} 


{% endfor %}
<br/>
<br/>
<br/>
<br/>
{% endblock %}

templates/adminreport/cancelInv.html
{% extends "base.html" %}
{% block body_block %}
<h1>Cancel Invoice</h1>
<form method ='POST' onsubmit="myButton.disabled = true; return true;">
{% csrf_token %}

{{ form.as_p }}
<input type ='submit' value='save'/>


{% endblock %}

templates/adminreport/cust_detail.html
{% extends "base.html" %}
{% block body_block %}
<p class="container">
  <div class="jumbotron">
    <h1><center>Detail</center></h1>
    <p><label class="control-label col-sm-2" >Customer Name</label>:<b> {{cust_details.Customer_Name}}</b> </p>
    <p><label class="control-label col-sm-2" >Address</label></label>: {{cust_details.Address}}</p>
    <p><label class="control-label col-sm-2" >City</label>: {{cust_details.City}}</p>
    <p><label class="control-label col-sm-2" >State</label>: {{cust_details.State}}</p>
    <p><label class="control-label col-sm-2" >GSTN of Customer</label>: {{cust_details.GSTN_of_Customer}}</p>
    <div class="btn-group" >
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'adminrep:CustEntryView' %}"><button type="button" class="btn btn-warning button2">See all Customer</button></a>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'adminrep:updateCustEntry' cust_details.Cust_Id %}"><button type="button" class="btn btn-danger button2">Update</button></a>
    
    
  </div>
  </div>
  

        

  </div>


{% endblock %}

templates/adminreport/cust_form_create.html
{% extends "base.html" %}
{% load static %}

{% block body_block %}
<script>
    $( function() {
      var availableTags = [
        
      ];
      $( "#cust_search" ).autocomplete({
        source: "{% url 'adminrep:autocomplete_cust_search'%}"
      });
    } );
  </script>
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

/* Button used to open the contact form - fixed at the bottom of the page */
.open-button {
  background-color: #555;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  opacity: 0.8;
  position: fixed;
  bottom: 23px;
  right: 28px;
  width: 280px;
}

/* The popup form - hidden by default */
.form-popup {
  display: none;
  position: fixed;
  bottom: 0;
  right: 15px;
  border: 3px solid #f1f1f1;
  z-index: 9;
}

/* Add styles to the form container */
.form-container {
  max-width: 1000px;
  padding: 5px;
  background-color: rgb(202, 219, 235);
  opacity: 1;
}

/* Full-width input fields */
.form-container input[type=text], .form-container input[type=password] {
  width: 100%;
  padding: 5px;
  margin: 5px 0 2px 0;
  border: none;
  background: #f1f1f1;
}

/* When the inputs get focus, do something */
.form-container input[type=text]:focus, .form-container input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Set a style for the submit/login button */
.form-container .btn {
  background-color: #4CAF50;
  color: white;
  border: none;
  cursor: pointer;
  width: 100%;
  margin-bottom:10px;
  opacity: 0.8;
}

/* Add a red background color to the cancel button */
.form-container .cancel {
  background-color: red;
}

/* Add some hover effects to buttons */
.form-container .btn:hover, .open-button:hover {
  opacity: 2;
}
</style>
</head>
<body>

<h2>Search for existing Customer</h2>
{% if error%}
<h3><font color='red'> Please select correct customer or create new customer</font></h3>
{% endif %}
<p>Click on the button at the bottom of this page to open the New Customer form.</p>
<center>
<form form ="myform" class="form-inline my-2 my-lg-0" action="{% url 'adminrep:oldCustForm' %}" method="get" onsubmit="myButton.disabled = true; return true;">
      <input class="form-control mr-sm-2 w-75" type="text" placeholder="Customer Name or Mobile number" required name="cust_search" id='cust_search'>
      <button name="myButton" class="btn btn-secondary my-2 my-sm-0 button1" type="submit">Select</button>
    </form>
</center>    <br>

<button class="open-button" onclick="openForm()">Create New Customer</button>

<div class="form-popup" id="myForm">
  
<form method ='POST' class="form-container" onsubmit="myButton1.disabled = true; return true;">
<h3>Customer Details</h3>
{% csrf_token %}

{% include 'form_template_cust.html' %}
<div class="col-sm-offset-2 col-sm-10">
    <input name="myButton1" type="submit" class='btn btn-success' value="Submit" />
    <button type="button" class="btn cancel" onclick="closeForm()">Close</button>


</div>

<script>
function openForm() {
  document.getElementById("myForm").style.display = "block";
}

function closeForm() {
  document.getElementById("myForm").style.display = "none";
}
</script>



{% endblock %}

templates/adminreport/custdetail_form.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
<script>
    $( function() {
      var availableTags = [
        
      ];
      $( "#id_Item_Catogory" ).autocomplete({
        source: "{% url 'bill:autocomplete_Catogory'%}"
      });
    } );
  </script>
<h1>
  
  Update Customer Name
  
    
</h1>
<br/>


  <form method="POST" onsubmit="myButton.disabled = true; return true;">
    {% csrf_token %}
    <div class="form-group">
    {% include 'form_template.html' %}
    <div class="col-sm-offset-2 col-sm-10">
    <input type="submit" name = "myButton" class='btn btn-success' value="Submit">
    

  </form>
      {% endblock %}

templates/adminreport/gst1.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<script>
    $( function() {
      var availableTags = [
        
      ];
      $( "#id_cust_name" ).autocomplete({
        source: "{% url 'adminrep:autocomplete_cust_search'%}"
      });
    } );
  </script>
<center><h1>sales report</h1></center>

<form  action="/adminrep/GST1" method="get" onsubmit="myButton.disabled = true; return true;">
<div class="form-group row">
      <label class="col-sm-2 col-form-label" for="id_cust_name"><b>Customer Name/All:</b></label></label>
	  <div class="col-sm-10">
      <input  class="form-control" type="text" name="id_cust_name" placeholder ='Customer Name/All'required id="id_cust_name">
     </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label" for="id_due_or_all"><b>Due or All report</b></label></label>
	  <div class="col-sm-10">
      <select class="form-control" id="id_due_or_all" name="id_due_or_all">
  <option value="All">All</option>
  <option value="Due">Due</option>
  </select>
      </div>
	  </div>

    <div class="form-group row" >
      <label class="col-sm-2 col-form-label" for="id_start_date"><b>Start Date(Billing date):</b></label></label>
	  <div class="col-sm-10">
      <input class=class="form-control" type="date" name="id_start_date"  required id="id_start_date">
 
    </div>
	</div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label"  for="id_end_date"><b>End Date(Billing date):</b></label></label>
	  <div class="col-sm-10">
      <input  type="date" name="id_end_date"  required id="id_end_date">
      </div>
    </div>
    <div class="form-group row">
    <input type="submit" class='btn btn-success' value="Submit">&nbsp;&nbsp;&nbsp;&nbsp;
    <input type="reset" class='btn btn-secondary' value="reset">
    </div>
    </form>

{% endblock %}

templates/adminreport/gst1_rep.html
{% extends "base.html" %}
{% block body_block %}

<center><h1>sales report between {{startdate}} and {{enddate}}</h1></center>




<table class="table table-striped table table-bordered">
<thead>
<tr>
<th>#</th>
<th>Customer Name</th>
<th>Mobile</th>
<th>Address</th>
<th>GST Number</th>
<th>Invoice Number</th>
<th>Invoice Date</th>
<th>Bill Amount</th>
<th>Amount Due</th>
</tr>
</thead>

{% for obj in search_result %}
<tr>
<td>{{forloop.counter}}</td>
<td>{{ obj.Customer_Name }}</td>
<td>{{ obj.Mob_No }}</td>
<td>{{ obj.Address }}</td>
<td>{{ obj.GSTN_of_Customer }}</td>
<td>{{ obj.Inv_Type }}-{{ obj.Inv_No }}</td>
<td>{{ obj.Inv_Date }}</td>
<td>{{ obj.total_bill_Amount }}</td>
<td>{{ obj.payment_left }}</td>
<td><a href="{% url 'adminrep:Invsearch' Inv=obj.Inv_Type q=obj.Inv_No %}">View</a></td>

</tr>


{% endfor %}
</table>

<h3>Total sale: {{total}}</h3>
<br/>
<h4>Table for hsn.csv</h4>
<br/>
<table class="table table-striped table table-bordered">
	<thead>
<tr>
<th>HSN</th>
<th>Description</th>
<th>Unit</th>
<th>Total Quantity</th>
<th>Total Value</th>
<th>Taxable Value</th>
<th>IGST</th>
<th>CGST</th>
<th>SGST</th>
<th>Cess</th>
<th>Rate</th>
</tr>
</thead>

{% for obj,val in parse.items %}

<td>{{val.Hsn_Code}}</td>
<td></td>
{% if val.unit == 'PCS' %}
<td>PCS-PIECES</td>
{% elif val.unit == 'MTR'%}
<td>MTR-METERS</td>
{% elif val.unit == 'DOZ'%}
<td>DOZ-DOZENS</td>
{% endif %}
<td>{{val.quanity}}</td>
<td>{{val.total_bill_Amount}}</td>
<td>{{val.Sale_Without_Tax}}</td>
<td>{{val.igst}}</td>
<td>{{val.cgst}}</td>
<td>{{val.sgst}}</td>
<td>0</td>
<td>0</td>

</tr>


{% endfor %}
</table>
<br/>
<h4>Table for without GST Number bill</h4>
<br/>
<table class="table table-striped table table-bordered">
	<thead>
<tr>
<th>State</th>
<th>Total Value</th>
<th>Taxable Value</th>
<th>IGST</th>
<th>CGST</th>
<th>SGST</th>
</tr>
</thead>

{% for obj,val in bill_without_gst.items %}

<td>{{val.state}}</td>
<td>{{val.total_bill_Amount}}</td>
<td>{{val.Total_without_tax}}</td>
<td>{{val.igst}}</td>
<td>{{val.cgst}}</td>
<td>{{val.sgst}}</td>

</tr>
{% endfor %}
</table>
<br/>
<h4>Table for Bill with GST Number</h4>
<br/>
<table class="table table-striped table table-bordered">
	<thead>
<tr>
<th>Invoice Number</th>
<th>Inv_Date</th>
<th>GST Number</th>
<th>Customer Name</th>
<th>Taxable Value</th>
<th>IGST</th>
<th>CGST</th>
<th>SGST</th>
<th>Total Amount</th>

</tr>
</thead>

{% for obj,val in bill_with_gst.items %}

<td>{{val.Inv}}</td>
<td>{{val.Inv_Date}}</td>
<td>{{val.GSTN_of_Customer}}</td>
<td>{{val.Customer_Name}}</td>
<td>{{val.Total_No_Tax_Sale}}</td>
<td>{{val.Igst_Tot_Sale}}</td>
<td>{{val.Cgst_Tot_Sale}}</td>
<td>{{val.Sgst_Tot_Sale}}</td>
<td>{{val.Total_Sale}}</td>


</tr>
{% endfor %}
</table>
<br/>
<br/>

{% endblock %}

templates/adminreport/payment.html
{% extends "base.html" %}
{% block body_block %}
<h1>Payment</h1>
<h6>Total bill amount is <font color='red'><b>{{grandTotal}}</b></font></h6>
<form method ='POST' onsubmit="myButton.disabled = true; return true;">
{% csrf_token %}

{% include 'form_template.html' %}
<div class="col-sm-offset-2 col-sm-10">
    <input type="submit" name = "myButton" class='btn btn-success' value="Submit" onclick=onclick="myFunction()"/>


    <script>
        function myFunction() {
          window.open("{% url 'bill:index'%}");
        }
        </script>
{% endblock %}