adminreport/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views


app_name = 'adminrep'

urlpatterns = [

    path('NewCustForm/',views.NewCustForm,name='NewCustForm'),
    path('payment/',views.payment,name='payment'),
    #path('delete/<int:pk>/',views.printDeleteView.as_view(),name='delete'),
    path('Invsearch/',views.Invsearch,name='Invsearch'),
    url(r'^Invsearch/(?P<Inv>\w+)/(?P<q>\w+)/$',views.Invsearch,name='Invsearch'),
    #re_path(r'^Invsearch\.+$',views.Invsearch,name='Invsearch'),
    path('paymentupdate/',views.paymentupdate,name='paymentupdate'),
    path('GST1/',views.GST1,name='GST1'),
    path('gst1Input/',views.gst1Input,name='gst1Input'),
    path('cancelInv/',views.cancelInv,name='cancelInv'),
    path('autocomplete_cust_search/',views.autocomplete_cust_search,name='autocomplete_cust_search'),
    path('oldCustForm/',views.oldCustForm,name='oldCustForm'),
    path('updateCustEntry/<int:pk>/',views.updateCustEntry.as_view(),name='updateCustEntry'),
    path('CustEntryView/',views.CustEntryView.as_view(),name='CustEntryView'),
    path('<int:pk>/',views.custDetailView.as_view(),name='detail'),
    


]

bill/urls.py
from django.urls import path
from . import views

app_name = 'bill'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('admin/',views.AdminView.as_view(),name='admin'),
    path('report/',views.ReportView.as_view(),name='report'),
    #path('print/',views.printView.as_view(),name='print'),
    path('admin_gst_list/',views.gstAdminListView.as_view(),name='admin_gst_list'),
    path('admin_nogst_list/',views.nogstAdminListView.as_view(),name='admin_nogst_list'),
    path('gst_list/',views.gstListView.as_view(),name='gst_list'),
    path('nogst_list/',views.nogstListView.as_view(),name='nogst_list'),
    path('create/',views.CreateSaleEntry.as_view(),name='create'),
    path('<int:pk>/',views.gstDetailView.as_view(),name='detail'),
    path('update/<int:pk>/',views.updateSaleEntry.as_view(),name='update'),
    path('delete/<int:pk>/',views.billDeleteView.as_view(),name='delete'),
    path('view/',views.viewSales.as_view(),name='viewSales'),
    path('search/',views.search,name='search'),
    path('search-form/', views.search_form,name='search-form'),
    path('Estimate/', views.Estimate,name='Estimate'),
    path('Invoice/', views.Invoice,name='Invoice'),
    path('stock/', views.stock.as_view(),name='stock'),
    path('stateOfSupply/',views.stateOfSupply,name='stateOfSupply'),
    path('autocomplete/', views.autocomplete,name='autocomplete'),
    path('autocomplete_Catogory/', views.autocomplete_Catogory,name='autocomplete_Catogory'),
]

billing/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from bill import views
from django.conf.urls import url
#from print import views

urlpatterns = [
    path('',views.IndexView.as_view()),
    #path('',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('admin/',admin.site.urls,name='admin'),
    path('bill/',include('bill.urls',namespace='bill')),
    path('print/',include('print.urls',namespace='print')),
    path('adminrep/',include('adminreport.urls',namespace='adminrep')),
    path('GST2A/',include('GSTR2A.urls',namespace='GST2A')),
    path('itemreturn/',include('itemreturn.urls',namespace='itemreturn')),

    
]

print/urls.py
from django.urls import path
from . import views


app_name = 'print'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('printview/',views.printview.as_view(),name='printview'),
    path('post_print_Form/',views.post_print_Form,name='post_print_Form'),
    path('update_print_Form/<int:pk>',views.update_print_Form,name='update_print_Form'), 
    path('get_print_Form/', views.get_print_Form,name='get_print_Form'),
    path('viewprint/',views.viewprint,name='viewprint'),
    path('delete/<int:pk>/',views.printDeleteView.as_view(),name='delete'),
    path('InvoicePrint/',views.InvoicePrint,name='InvoicePrint'),
    path('quick_print_Form/',views.quick_print_Form,name='quick_print_Form'),
    path('autocomplete/', views.autocomplete,name='autocomplete'),
    path('testPrint/', views.testPrint,name='testPrint'),
    
    
]

print/forms.py
from django import forms

class printForm(forms.Form):  
    Item_Code             = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Item_Name             = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Item_Catogory         = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    HSN_Code              = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Quatity_Sold          = forms.FloatField()
    Unit                  = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Rate_Of_Sale          = forms.FloatField()
    IGST_Percent          = forms.FloatField()
    CGST_Percent          = forms.FloatField()
    SGST_Percent          = forms.FloatField()
    GST_Type              = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Total                 = forms.FloatField(widget = forms.HiddenInput(), required = False)
    Gross_Total           = forms.FloatField(widget = forms.HiddenInput(), required = False)
    Total_CGST            = forms.FloatField(widget = forms.HiddenInput(), required = False)
    Total_SGST            = forms.FloatField(widget = forms.HiddenInput(), required = False)
    Total_IGST            = forms.FloatField(widget = forms.HiddenInput(), required = False)

    def clean_GST_Type(self):
        data = self.cleaned_data['GST_Type']
        if data == "N":
            raise forms.ValidationError("Try Estimate billing")
        return data

class estimateForm(forms.Form):  
    Item_Code             = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Item_Name             = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Item_Catogory         = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    HSN_Code              = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Quatity_Sold          = forms.FloatField()
    Unit                  = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Rate_Of_Sale          = forms.FloatField()
    IGST_Percent          = forms.FloatField()
    CGST_Percent          = forms.FloatField()
    SGST_Percent          = forms.FloatField()
    GST_Type              = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Total                 = forms.FloatField(widget = forms.HiddenInput(), required = False)
    Gross_Total           = forms.FloatField(widget = forms.HiddenInput(), required = False)
    Total_CGST            = forms.FloatField(widget = forms.HiddenInput(), required = False)
    Total_SGST            = forms.FloatField(widget = forms.HiddenInput(), required = False)
    Total_IGST            = forms.FloatField(widget = forms.HiddenInput(), required = False)

print/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,DetailView,ListView,DeleteView,CreateView,UpdateView,View
from .models import salesDb
from bill.models import billSaleEntry
from django.urls import reverse_lazy,reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.db.models import Q
from .forms import printForm,estimateForm
from django.db.models import Sum
from adminreport.models import SaleReport,CustDetail
from num2words import num2words
from datetime import datetime
from django.http.response import JsonResponse
import re

# Create your views here.
ros =0
Qua =0
cgst =0
sgst =0
igst =0
total = 0
total_cgst= 0
total_igst= 0
total_sgst= 0
TotalNoGST = 0

def autocomplete(request):
    model = billSaleEntry
    q= request.GET.get('term')
    qs =model.objects.filter(Q(Item_Code__iexact=q)|Q(Item_Name__istartswith = q)).values('Item_Name')
    item_name_lst =list()
    for item in qs.values():
        #print(item)
        sp = item['Rate_Of_Sale']
        sper = item['IGST_Percent'] +item['SGST_Percent']+item['CGST_Percent']
        sp_ajax = sp+sp*(sper/100)
        val = item['Item_Name']+','+item['Item_Catogory']+',SELL:'+str(sp_ajax)+',code:'+str(item['Item_Code'])
        item_name_lst.append(val)
        #item_cat_lst.append(item['Item_Catogory'])
        #item_sp_lst.append(item['Rate_Of_Sale'])
        
    return JsonResponse(item_name_lst,safe=False)

#  bill index page
class IndexView(TemplateView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'index.html'

#bill index page
class printview(TemplateView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'print/index.html'

#calculation of GST
def gst_cal(rateOfSale,gst,quat):
    cal = rateOfSale*quat*gst
    ret_cal =cal/100
    ret_tot =float("{0:.2f}".format(ret_cal))
    return ret_tot

#calculation of total EXCLUDING  GST
def totalNoGST(rateOfSale,quat):
    cal = rateOfSale*quat
    ret_tot =float("{0:.2f}".format(cal))
    return ret_tot

#Create/update item by search result (this is on confirmation page)
def get_print_Form(request):
    q = request.POST['q']
    request.session["q"] = q
    printVals = billSaleEntry.objects.filter(Item_Code__exact=q)
    for printVal in printVals:
        initial_data ={

            "ItemCode" :printVal.Item_Code,
            "ItemName" :printVal.Item_Name
             }
    return render(request,"print/print_add_confirm.html",context=initial_data)

#Create/Update item by search result (Most valve are retived from billSaleEntry only quantity and rate of sale
# can be edited)
#It is use to calculate some values on input
def post_print_Form(request):
    
    q = request.session['q']
    placeOfSupply= request.session['placeOfSupply']
    bill_type=request.session['bill_type']
    #print("q=",q)
    #print("bill_type=",bill_type)
    printVals = billSaleEntry.objects.filter(Item_Code__exact=q)
    #print("printvals",printVals)
    if bill_type=='IN':
        my_form = printForm()
    else:
        my_form = estimateForm()
    #print("My orm",my_form)
    for printVal in printVals:
        tot_gst = printVal.IGST_Percent+printVal.SGST_Percent+printVal.CGST_Percent
        if placeOfSupply =="Bihar(10)":
            IGST_Per_Val=0
            SGST_Per_Val=float("{0:.2f}".format(tot_gst/2))
            CGST_Per_Val=float("{0:.2f}".format(tot_gst/2))
        
        else:
            IGST_Per_Val=float("{0:.2f}".format(tot_gst))
            SGST_Per_Val=0
            CGST_Per_Val=0
        #print(IGST_Per_Val,SGST_Per_Val,CGST_Per_Val)
        initial_data ={

            "Item_Code" :printVal.Item_Code,
            "Item_Name" :printVal.Item_Name,
            "Item_Catogory":printVal.Item_Catogory,
            "HSN_Code" :printVal.HSN_Code,
            "Unit" :printVal.Unit,
            "Rate_Of_Sale" :printVal.Rate_Of_Sale,
            "Rate_Of_Purchase" :printVal.Rate_Of_Purchase,
            "IGST_Percent" : IGST_Per_Val,
            "SGST_Percent" : SGST_Per_Val,
            "CGST_Percent" : CGST_Per_Val,
            "GST_Type" : printVal.GST_Type 

            }   
    if bill_type=='IN':
        my_form = printForm(request.POST or None,initial=initial_data)
    else:
        my_form = estimateForm(request.POST or None,initial=initial_data)
    
    if my_form.is_valid():
        global ros,Qua,cgst,sgst,igst,total,totalNoGST,total_cgst,total_igst,total_sgst,NoGST
        ros = my_form.cleaned_data["Rate_Of_Sale"]
        Qua = my_form.cleaned_data["Quatity_Sold"]
        cgst = my_form.cleaned_data["CGST_Percent"]
        igst = my_form.cleaned_data["IGST_Percent"]
        sgst = my_form.cleaned_data["SGST_Percent"]
        total_cgst = gst_cal(ros,cgst,Qua)
        total_igst = gst_cal(ros,igst,Qua)
        total_sgst = gst_cal(ros,sgst,Qua)
        NoGST = totalNoGST(ros,Qua)
        total = float("{0:.2f}".format(NoGST+total_cgst+total_igst+total_sgst))
        my_form.cleaned_data['Total']= total
        my_form.cleaned_data['Gross_Total']=  NoGST
        my_form.cleaned_data['Total_CGST']= total_cgst
        my_form.cleaned_data['Total_IGST']= total_igst
        my_form.cleaned_data['Total_SGST']= total_sgst
        my_form.cleaned_data['session_id'] = request.session.session_key
        #print(my_form.cleaned_data)
        salesDb(**my_form.cleaned_data).save()
        return HttpResponseRedirect(reverse('print:viewprint'))


    #del request.session["q"]
    return render(request,"print/print_form_create.html",{"form":my_form})

# create list view for all entry of printing database

def viewprint(request):
    bill_type=request.session['bill_type']
    placeOfSupply= request.session['placeOfSupply']
    
    #if bill_type=='IN':

    viewprint = salesDb.objects.filter(session_id=request.session.session_key).order_by('insert_date')
    session_id = request.session.session_key
    session = request.user
    error_list = list()
    checkList = list()
    opDict = dict()
    for itemLoop in viewprint.values():
        opDict['Item_Name']= itemLoop['Item_Code']
        #print(viewprint.values())

        if itemLoop['Item_Code'] not in checkList:
            checkList.append(itemLoop['Item_Code'])
        else:
            error_list.append(itemLoop['Item_Code'])
    #print(error_list)
        
    grandTotal = float("{0:.2f}".format(salesDb.objects.filter(session_id=request.session.session_key).aggregate(Sum('Total'))['Total__sum'] or 0.00))
    contexDict = {'viewprint':viewprint,
                    'grandTotal':grandTotal,
                    'bill_type':bill_type,
                    'placeOfSupply':placeOfSupply,
                    'errorList':error_list,}

    return render(request,'print/view_bill.html',context=contexDict)

def testPrint(request):
    #bill_type=request.session['bill_type']
    #placeOfSupply= request.session['placeOfSupply']
    
    #if bill_type=='IN':

    viewprint = salesDb.objects.filter(session_id=request.session.session_key)
    for i in viewprint:
        i.Rate_Of_Sale = float("{0:.2f}".format(i.Rate_Of_Sale + (i.IGST_Percent + i.CGST_Percent + i.SGST_Percent)*(i.Rate_Of_Sale/100)))
    grandTotal = float("{0:.2f}".format(salesDb.objects.filter(session_id=request.session.session_key).aggregate(Sum('Total'))['Total__sum'] or 0.00))
    contexDict = {'viewprint':viewprint,
                    'grandTotal':grandTotal
                    }
    salesDb.objects.filter(session_id=request.session.session_key).delete()

    return render(request,'print/test.html',context=contexDict)

#Update item by primary key (Most valve are retived from billSaleEntry only quantity and rate of sale
# can be edited)
#It is use to calculate some values on input  
def update_print_Form(request,pk):
    bill_type=request.session['bill_type']
    printVal = salesDb.objects.get(id =pk)
    
    initial_data ={
            "Item_Code" :printVal.Item_Code,
            "Item_Name" :printVal.Item_Name,
            "Quatity_Sold": printVal.Quatity_Sold,
            "Item_Catogory":printVal.Item_Catogory,
            "HSN_Code" :printVal.HSN_Code,
            "Unit" :printVal.Unit,
            "Rate_Of_Sale" :printVal.Rate_Of_Sale,
            "IGST_Percent" : printVal.IGST_Percent,
            "SGST_Percent" : printVal.SGST_Percent,
            "CGST_Percent" : printVal.CGST_Percent,
            "GST_Type" : printVal.GST_Type

             }     
    if bill_type=='IN':
        my_form = printForm(request.POST or None,initial=initial_data)
    else:
        my_form = estimateForm(request.POST or None,initial=initial_data)
    
    if my_form.is_valid():
        global ros,Qua,cgst,sgst,igst,total,totalNoGST,total_cgst,total_igst,total_sgst,NoGST
        my_form.cleaned_data['id']= pk
        ros = my_form.cleaned_data["Rate_Of_Sale"]
        Qua = my_form.cleaned_data["Quatity_Sold"]
        cgst = my_form.cleaned_data["CGST_Percent"]
        igst = my_form.cleaned_data["IGST_Percent"]
        sgst = my_form.cleaned_data["SGST_Percent"]
        total_cgst = gst_cal(ros,cgst,Qua)
        total_igst = gst_cal(ros,igst,Qua)
        total_sgst = gst_cal(ros,sgst,Qua)
        NoGST = totalNoGST(ros,Qua)
        total = float("{0:.2f}".format(NoGST+total_cgst+total_igst+total_sgst))
        my_form.cleaned_data['Total']= total
        my_form.cleaned_data['Gross_Total']=  NoGST
        my_form.cleaned_data['Total_CGST']= total_cgst
        my_form.cleaned_data['Total_IGST']= total_igst
        my_form.cleaned_data['Total_SGST']= total_sgst
        my_form.cleaned_data['session_id']=request.session.session_key
 
        salesDb(**my_form.cleaned_data).save()
        
        return HttpResponseRedirect(reverse('print:viewprint'))

    return render(request,"print/print_form_create.html",{"form":my_form})

#delete values from print database
class printDeleteView(DeleteView):

templates/print/error_add_billing.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
<script>
    $( function() {
      var availableTags = [
        
      ];
      $( "#q_auto" ).autocomplete({
        minLength: 2,
        source: "{% url 'print:autocomplete'%}"
      });
    } );
    </script>
<center><h4><font color="red">{{error}}</font> </h4></center>
<br/>
<br/>

<br/>
<form form ="myform" class="form-inline my-2 my-lg-0" action="/print/quick_print_Form/" method="get" onsubmit="myButton.disabled = true; return true;">
  <input class="form-control mr-sm-2 w-50" type="text" placeholder="ItemCode/Item name" required name="q" id='q_auto'>
  <input class="form-control mr-sm-2" type="text" placeholder="Quatity"  required name="Quat">
  <input class="form-control mr-sm-2" type="text" placeholder="Sell Price"  name="sellPrice">
  <button name = "myButton" class="btn btn-secondary my-2 my-sm-0 button1" type="submit">Billing</button>
</form>

<br>
  To see data already added<a class="btn btn-success" href="{% url 'print:viewprint' %} ">View</a>


{% endblock %}

templates/print/index.html
{% extends "base.html" %}
{% block body_block %}
<center><h1>Billing Main Page</h1></center>
{%if error%}
<center><h5><font color = 'red'>Invoice {{Inv}}-{{q}} not found Please recheck</font></h5></center>
{%endif%}
<br>
<form class="form-inline my-2 my-lg-0" action="/adminrep/Invsearch" method="get" onsubmit="myButton.disabled = true; return true;">

    <h4>Invoice Number &nbsp;</h4>
    <select class="form-control mr-sm-2" name="Inv">
    <option value="IN">IN</option>
    <option value="EST">EST</option>
    
    </select><b>- &nbsp;</b><input class="form-control mr-sm-2" type="number" placeholder="Search" name="q" required >
      <button class="btn btn-secondary my-2 my-sm-0 button1" type="submit">Search</button>
    </form>
    <br>
<br>
<a href="{% url 'print:viewprint' %}"><button type="button" class="btn btn-success">All items added for billing</button></a>
<br><br>
<a href="{% url 'bill:Estimate'%}"><button type="button" class="btn btn-success">Estimate Bill</button></a>
<br><br>
<a href="{% url 'bill:Invoice'%}"><button type="button" class="btn btn-success">Invoice Bill</button></a>
{% endblock %}

templates/print/print_add_confirm.html
{% extends "base.html" %}
{% block body_block %}
<h1>Add to print?</h1>
<p>

<h3>Do you want to Add Item of Item Code {{ ItemCode }}<p>
Item name is {{ ItemName }}</p></h3>


</p>
<a class="nav-link" href="{% url 'print:post_print_Form' %}"><button class="btn btn-secondary my-2 my-sm-0" type="submit">Confirm</button></a>


{% endblock %}

templates/print/print_form_create.html
{% extends "base.html" %}
{% block body_block %}
<h1><center>Print view</center></h1>
<form method ='POST'>
{% csrf_token %}

{{ form.as_p }}
<input type ='submit' value='save'/>


{% endblock %}

templates/print/printdb_confirm_delete.html
{% extends "base.html" %}

{% block body_block %}
<h1>Delete {{printDeleteView.Item_Name}} {{printDeleteView.Item_Catogory}} {{printDeleteView.Quatity_Sold}}{{printDeleteView.Unit}} ?</h1>

<form method="post" onsubmit="myButton.disabled = true; return true;">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'print:viewprint' %} ">Cancel</a>


</form>

{% endblock %}

templates/print/stateOfSupply.html
{% extends "base.html" %}
{% block body_block %}
<center><h1>State Of Supply</h1></center>
<br>
<br>
<form class="form-inline my-2 my-lg-0" action="/bill/stateOfSupply" method="get" onsubmit="myButton.disabled = true; return true;">

    <h4>Select State of Supply&nbsp;</h4>
    <select class="form-control mr-sm-2" name="placeOfSupply">
    <option value="Bihar(10)">Bihar(10)</option>
    <option value="Jharkhand(20)">Jharkhand(20)</option>
    <option value="West Bengal(19)">West Bengal(19)</option>
    <option value="Uttar Pradesh(09)">Uttar Pradesh(09)</option>
    
    </select>
      <button class="btn btn-secondary my-2 my-sm-0 button1" type="submit">Submit</button>
    </form>
    <br>

{% endblock %}

templates/print/view_bill.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
<style>
.open-button {
    background-color: #555;
    color: white;
    padding: 16px 20px;
    border: none;
    cursor: pointer;
    opacity: 0.8;
    position: fixed;
    bottom: 23px;
    right: 28px;
    width: 280px;
  }
</style>
  <script>
    $( function() {
      var availableTags = [
        
      ];
      $( "#q_auto" ).autocomplete({
        source: "{% url 'print:autocomplete'%}"
      });
    } );
    </script>
<h1>Item Added Summary</h1><br>
<center>
<form form ="myform" class="form-inline my-2 my-lg-0" action="/print/quick_print_Form/" method="get" onsubmit="myButton.disabled = true; return true;">
      <input class="form-control mr-sm-2 w-50" type="text" placeholder="ItemCode/Item name" required name="q" id='q_auto'>
      <input class="form-control mr-sm-2" type="text" placeholder="Quatity"  required name="Quat">
      <input class="form-control mr-sm-2" type="text" placeholder="Sell Price"  name="sellPrice">
      <button name = "myButton" class="btn btn-secondary my-2 my-sm-0 button1" type="submit">Billing</button>
    </form>
</center>    <br>
{% if errorval == 'NoVal'%}
    No ItemCode {{Itemcode_got}} found

{% endif%}
<h5>State of Supply : {{placeOfSupply}}
{% if bill_type == 'IN'%}
    Bill Type = Invoice Bill
    {% elif bill_type == 'EST'%}
    Bill Type =  Estimation
{% endif%}
</h5>
<table class="table table-bordered table-condensed">
<thead>
    <tr>
    <th>ItemName</th>
    <th>ItemCatogory</th>
    <th>Quatity</th>
    <th>Final Price</th>
    <th>Tax%</th>
    <th>Total No Tax</th>
    <th>Total</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for obj in viewprint %}
        {% if obj.Item_Code in errorList %}
            <tr bgcolor="yellow">
        {% elif obj.Rate_Of_Purchase > obj.Rate_Of_Sale %}
            <tr bgcolor="red">
        {% else %}
            <tr bgcolor="white">
        {% endif %}
        <td>{{ obj.Item_Name }}</td>
        <td>{{ obj.Item_Catogory }}</td>
        <td>{{ obj.Quatity_Sold }} {{ obj.Unit }}</td>
        <td>{{ obj.FinalSP }}</td>
        <td>{{ obj.FinalGST }}</td>
        <td>{{ obj.Gross_Total }}</td>
        <td>{{ obj.Total }}</td>
        <td><a href="{% url 'print:update_print_Form' obj.id %}">edit</a></td>
        <td><a class="btn btn-danger" href="{% url 'print:delete' obj.id %}">delete</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>
<h3>Grand Total={{grandTotal}}
<br>
<br>
<br>



<center><a type="button" class="btn btn-primary active" href="{% url 'adminrep:NewCustForm'%}">Add customer Details</a></center>
<br>
<br>
<br>
<center><a type="button" class="btn btn-primary active" href="{% url 'print:testPrint'%}">Test</a></center>

<button class = 'open-button' onclick="myFunction()">Add New Item</button>

<script>
function myFunction() {
  window.open("{% url 'bill:create'%}", "_blank", "toolbar=yes,scrollbars=yes,resizable=yes,top=100,left=0,width=2000,height=1000");
}
</script>
    
{% endblock %}

templates/print/view_sales.html
{% extends "base.html" %}
{% block body_block %}
<h1>Bill</h1>

<table border="1">
<thead>
    <tr>
    <th>ItemCode</th>
    <th>ItemName</th>
    <th>HSNCode</th>
    <th>Quatity</th>
    <th>RateOfPurchase</th>
    <th>Unit</th>
    <th>RateOfSale</th>
    <th>CGST%</th>
    <th>SGST%</th>
    <th>typeGST</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for obj in viewSales %}
    <tr>
        <td>{{ obj.ItemCode }}</td> 
        <td>{{ obj.ItemName }}</td>
        <td>{{ obj.HSNCode }}</td>
        <td>{{ obj.Quatity }}</td>
        <td>{{ obj.RateOfPurchase }}</td>
        <td>{{ obj.unit }}</td>
        <td>{{ obj.RateOfSale }}</td>
        <td>{{ obj.CGST_P }}</td>
        <td>{{ obj.SGST_P }}</td>
        <td>{{ obj.typeGST }}</td>
        <td><a href="{% url 'bill:update' obj.ItemCode %}">edit</a></td>
        <td><a class="btn btn-danger" href="{% url 'bill:delete' obj.ItemCode %}">delete</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>
{% endblock %}