GSTR2A/urls.py
from django.urls import path
from . import views

app_name = 'GST2A'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('GST2Aindex/',views.GST2Aindex.as_view(),name='GST2Aindex'),
    path('CreateGST2A/',views.CreateGST2A.as_view(),name='CreateGST2A'),
    path('UpdateGSTR2A/<int:pk>/',views.UpdateGSTR2A.as_view(),name='UpdateGSTR2A'),
    path('GSTR2AList/',views.GSTR2AList.as_view(),name='GSTR2AList'),
    path('GSTR2ADeleteView/<int:pk>/',views.GSTR2ADeleteView.as_view(),name='GSTR2ADeleteView'),
    path('search/',views.search,name='search'),
    path('gst2Input/',views.gst2Input,name='gst2Input'),
    path('GSTR2AFilling/',views.GSTR2AFilling,name='GSTR2AFilling'),
    path('autocomplete/',views.autocomplete,name='autocomplete'),
    path('autocomplete_gst_no/',views.autocomplete_gst_no,name='autocomplete_gst_no'),
    path('autocomplete_Supplier/',views.autocomplete_Supplier,name='autocomplete_Supplier'),
    path('DetailGSTR2A/<int:pk>/',views.DetailGSTR2A.as_view(),name='DetailGSTR2A'),
    
    
]

adminreport/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views


app_name = 'adminrep'

urlpatterns = [

    path('NewCustForm/',views.NewCustForm,name='NewCustForm'),
    path('payment/',views.payment,name='payment'),
    #path('delete/<int:pk>/',views.printDeleteView.as_view(),name='delete'),
    path('Invsearch/',views.Invsearch,name='Invsearch'),
    url(r'^Invsearch/(?P<Inv>\w+)/(?P<q>\w+)/$',views.Invsearch,name='Invsearch'),
    #re_path(r'^Invsearch\.+$',views.Invsearch,name='Invsearch'),
    path('paymentupdate/',views.paymentupdate,name='paymentupdate'),
    path('GST1/',views.GST1,name='GST1'),
    path('gst1Input/',views.gst1Input,name='gst1Input'),
    path('cancelInv/',views.cancelInv,name='cancelInv'),
    path('autocomplete_cust_search/',views.autocomplete_cust_search,name='autocomplete_cust_search'),
    path('oldCustForm/',views.oldCustForm,name='oldCustForm'),
    path('updateCustEntry/<int:pk>/',views.updateCustEntry.as_view(),name='updateCustEntry'),
    path('CustEntryView/',views.CustEntryView.as_view(),name='CustEntryView'),
    path('<int:pk>/',views.custDetailView.as_view(),name='detail'),
    


]

bill/urls.py
from django.urls import path
from . import views

app_name = 'bill'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('admin/',views.AdminView.as_view(),name='admin'),
    path('report/',views.ReportView.as_view(),name='report'),
    #path('print/',views.printView.as_view(),name='print'),
    path('admin_gst_list/',views.gstAdminListView.as_view(),name='admin_gst_list'),
    path('admin_nogst_list/',views.nogstAdminListView.as_view(),name='admin_nogst_list'),
    path('gst_list/',views.gstListView.as_view(),name='gst_list'),
    path('nogst_list/',views.nogstListView.as_view(),name='nogst_list'),
    path('create/',views.CreateSaleEntry.as_view(),name='create'),
    path('<int:pk>/',views.gstDetailView.as_view(),name='detail'),
    path('update/<int:pk>/',views.updateSaleEntry.as_view(),name='update'),
    path('delete/<int:pk>/',views.billDeleteView.as_view(),name='delete'),
    path('view/',views.viewSales.as_view(),name='viewSales'),
    path('search/',views.search,name='search'),
    path('search-form/', views.search_form,name='search-form'),
    path('Estimate/', views.Estimate,name='Estimate'),
    path('Invoice/', views.Invoice,name='Invoice'),
    path('stock/', views.stock.as_view(),name='stock'),
    path('stateOfSupply/',views.stateOfSupply,name='stateOfSupply'),
    path('autocomplete/', views.autocomplete,name='autocomplete'),
    path('autocomplete_Catogory/', views.autocomplete_Catogory,name='autocomplete_Catogory'),
]

billing/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from bill import views
from django.conf.urls import url
#from print import views

urlpatterns = [
    path('',views.IndexView.as_view()),
    #path('',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('admin/',admin.site.urls,name='admin'),
    path('bill/',include('bill.urls',namespace='bill')),
    path('print/',include('print.urls',namespace='print')),
    path('adminrep/',include('adminreport.urls',namespace='adminrep')),
    path('GST2A/',include('GSTR2A.urls',namespace='GST2A')),
    path('itemreturn/',include('itemreturn.urls',namespace='itemreturn')),

    
]

itemreturn/urls.py
from django.urls import path
from . import views

app_name = 'itemreturn'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('returnindex/',views.returnindex.as_view(),name='returnindex'),
    path('CreatereturnEntry/',views.CreatereturnEntry.as_view(),name='CreatereturnEntry'),
    #path('<int:pk>/',views.gstDetailView.as_view(),name='detail'),
    #path('update/<int:pk>/',views.updateSaleEntry.as_view(),name='update'),
    #path('delete/<int:pk>/',views.billDeleteView.as_view(),name='delete'),
    
]

print/urls.py
from django.urls import path
from . import views


app_name = 'print'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('printview/',views.printview.as_view(),name='printview'),
    path('post_print_Form/',views.post_print_Form,name='post_print_Form'),
    path('update_print_Form/<int:pk>',views.update_print_Form,name='update_print_Form'), 
    path('get_print_Form/', views.get_print_Form,name='get_print_Form'),
    path('viewprint/',views.viewprint,name='viewprint'),
    path('delete/<int:pk>/',views.printDeleteView.as_view(),name='delete'),
    path('InvoicePrint/',views.InvoicePrint,name='InvoicePrint'),
    path('quick_print_Form/',views.quick_print_Form,name='quick_print_Form'),
    path('autocomplete/', views.autocomplete,name='autocomplete'),
    path('testPrint/', views.testPrint,name='testPrint'),
    
    
]

templates/admin.html
{% extends "base.html" %}

{% block body_block %}

{% load static %}
<script src={% static 'bill/js/pass.js' %} type="text/javascript">
</script>
<ol>
    <li><button type="button" class="btn btn-outline-primary" class="btn btn-info" ><a href="{% url 'bill:admin_gst_list' %}">Admin Report GST</a></button></li>

    <p></p>
    <li><button type="button" class="btn btn-outline-primary" class="btn btn-info" ><a href="{% url 'bill:admin_nogst_list' %}">Admin Non Report GST</a></button></li>
<p></p>
<li><button type="button" class="btn btn-outline-primary" class="btn btn-info" ><a href="{% url 'admin:index' %}">Non Report GST</a></button></ol></li>
</ol>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'bill/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bill/css/jquery-ui.css' %}">
  <script src="{% static 'bill/js/jquery-1.12.4.js' %}"></script>
  <script src="{% static 'bill/js/jquery-ui.js' %}"></script>
  {% block anyscript %}

      {% endblock %}
  <script>
     function printpage() {
        //Get the print button and put it into a variable
        var printButton = document.getElementById("printpagebutton");
        //Set the print button visibility to 'hidden' 
        printButton.style.visibility = 'hidden';
        //Print the page content
        window.print()
        printButton.style.visibility = 'visible';
    }
function validateForm() {
  var x = document.forms["searchForm"]["q"].value;
  if (x == "") {
    alert("Search Must be filled out");
    return false;
  }
}
</script>
  <script src={% static 'bill/js/bootstrap.min.js' %}></script>

  </script>
  <script>
    $( function() {
      var availableTags = [
        
      ];
      $( "#q" ).autocomplete({
        minLength: 1,
        source: "{% url 'bill:autocomplete'%}"
      });
    } );

    
    </script>
  <style>
    table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
input:read-only {
  background-color: #dddddd;
}
@media print {
  #printPageButton {
    display: none;
  }
}
button {
  width: 300px;
  font-size: 24px;
}

.button1{
  width: 100px;
}
.button2{
  width: 125px;
}
.button3{
  width: 150px;
}
  </style>

<title>
{% block title %}

      {% endblock %}
</title>

 
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'bill:index' %}" >Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bill:stock' %}">Stock</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'print:printview' %}">Billing</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'GST2A:GST2Aindex' %}">Supplier</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'itemreturn:returnindex' %}">Return</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bill:report' %}">Report</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bill:admin' %}">Admin</a>
      </li>

    </ul>
    <form name ="searchForm" class="form-inline my-2 my-lg-0" action="/bill/search/" onsubmit="return validateForm()" method="get">
      <input class="form-control mr-sm-2 w-80 ui-autocomplete-input" type="text" placeholder="Search" name="q" id ="q">
      <button class="btn btn-secondary my-2 my-sm-0 button1" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container">
<p>

</p>

{% block body_block %}

      {% endblock %}

</div>
  </body>
</html>

templates/form_template.html
{% for field in form %}
    <div class="form-horizontal">
        <div class="col-sm-offset-2 col-xs-5">
            <span class="text-danger small">{{ field.error }}</span>
        </div >
        

        <div class="form-inline form-group">
      <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
      <div class="col-sm-10">{{ field }}
      </div>
    </div>


    </div>
    {% endfor %}

templates/form_template_cust.html
{% for field in form %}
    <div class="form-horizontal">
        <div class="col-sm-offset-2 col-xs-5">
            <span class="text-danger small">{{ field.error }}</span>
        </div >
        

        <div class="form-inline form-group">
      <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
      <div class="col-sm-10">{{ field }}
      </div>
    </div>


    </div>
    {% endfor %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
<a href="{% url 'bill:Estimate'%}"><button type="button" class="btn btn-success btn-lg btn-block">Estimate Bill</button></a>
<br>
<br>
<br>
<br>
<a href="{% url 'bill:Invoice'%}"><button type="button" class="btn btn-success btn-lg btn-block">Invoice Bill</button></a>

<br>
<br>
<br>
<script>
    $( function() {
      var availableTags = [
        
      ];
      $( "#q2" ).autocomplete({
        minLength: 1,
        source: "{% url 'bill:autocomplete'%}"
      });
    } );
    </script>
<div class="input-group">
    <input class="form-control border rounded-pill" type="search" placeholder="search item here" id="q2">
</div>
{% endblock %}

templates/nobase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
      <style>
    table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
  </style>
</head>
<body>
{% block body_block %}

      {% endblock %}
</body>
</html>

templates/report.html
{% extends "base.html" %}
{% block body_block %}

    <a href="{% url 'adminrep:gst1Input' %}"><button type="button" class="btn btn-outline-success" class="btn btn-info" >Sales report</button></a>
    <p></p>
    <a href="{% url 'GST2A:gst2Input' %}"><button type="button" class="btn btn-outline-success" class="btn btn-info" >Purchase report</button></a>
    
    <p></p>
    <a href="{% url 'adminrep:CustEntryView' %}"><button type="button" class="btn btn-outline-success" class="btn btn-info" >Customer</button></a>
    
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block body_block %}
<h1>Bill Search form</h1>
<br>
<br>
<div>
{% if search_result %}
    <table border="1" id = 'myTable'>
        <thead>
            <tr>
    <th onclick="sortTable1(0)">ItemCode</th>
    <th onclick="sortTable(1)">ItemName</th>
    <th onclick="sortTable(2)">Item_Catogory</th>
    <th onclick="sortTable1(3)">HSNCode</th>
    <th onclick="sortTable1(4)">Quatity Left In Stock</th>
    <th onclick="sortTable(5)">Unit</th>
    
    <th onclick="sortTable1(6)">Rate_Of_Sale</th>
    <th onclick="sortTable1(7)">IGST%</th>
    <th onclick="sortTable1(8)">CGST%</th>
    <th onclick="sortTable1(9)">SGST%</th>
    <th onclick="sortTable(10)">GST_Type</th>
    </tr>
        </thead>
        <tbody>
            {% for obj in search_result %}
                <tr>
            <td>{{ obj.Item_Code }}</td>
            <td>{{ obj.Item_Name }}</td>
            <td>{{ obj.Item_Catogory }}</td>
            <td>{{ obj.HSN_Code }}</td>
            <td>{{ obj.Quatity_in_stock }}</td>
            <td>{{ obj.Unit }}</td>
            <td>{{ obj.Rate_Of_Sale }}</td>
            
            <td>{{ obj.IGST_Percent }}</td>
            <td>{{ obj.CGST_Percent }}</td>
            <td>{{ obj.SGST_Percent }}</td>
            <td>{{ obj.GST_Type }}</td>
                    <td><form class="form-inline my-2 my-lg-0" action="{% url 'print:get_print_Form' %}" method="post">
                    {% csrf_token %}
                    <input  type="text" placeholder="Search" name="q" value = {{ obj.Item_Code }} hidden>
                    <a><button class="btn btn-secondary my-2 my-sm-0 button2" type="submit">
                    Add to Billing</button></a></form></td>
                    <td><a href="{% url 'bill:update' obj.Item_Code %}">edit</a></td>
                    <td><a class="btn btn-danger" href="{% url 'bill:delete' obj.Item_Code %}">delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
     {% else %}
        <li style="color:red">No obj</li>
    {% endif %}
{% endblock %}
</div>

templates/view_sales.html
{% extends "base.html" %}
{% block body_block %}
<h1>Bill</h1>

<table border="1">
<thead>
    <tr>
    <th>ItemCode</th>
    <th>ItemName</th>
    <th>HSNCode</th>
    <th>Quatity</th>
    <th>RateOfPurchase</th>
    <th>no_of_piece_in_qty</th>
    <th>RateOfSale</th>
    <th>RateOfGST</th>
    <th>typeGST</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for obj in viewSales %}
    <tr>
        <td>{{ obj.ItemCode }}</td>
        <td>{{ obj.ItemName }}</td>
        <td>{{ obj.HSNCode }}</td>
        <td>{{ obj.Quatity }}</td>
        <td>{{ obj.RateOfPurchase }}</td>
        <td>{{ obj.unit }}</td>
        <td>{{ obj.RateOfSale }}</td>
        <td>{{ obj.CGST_P }}</td>
        <td>{{ obj.SGST_P }}</td>
        <td>{{ obj.typeGST }}</td>
        <td><a href="{% url 'bill:update' obj.ItemCode %}">edit</a></td>
        <td><a class="btn btn-danger" href="{% url 'bill:delete' obj.ItemCode %}">delete</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>
{% endblock %}